# Generated by Django 5.2.4 on 2025-07-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='required_inventory',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.inventoryitem'),
        ),
    ]
