# Generated by Django 5.2.4 on 2025-07-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_folder_project_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='projects.folder'),
        ),
    ]
