# Generated by Django 5.2.4 on 2025-07-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_cover_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
